/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import cordinator.Cordinator;
import javax.swing.JLabel;

/**
 *
 * @author milic
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glavna forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClan = new javax.swing.JMenu();
        jMenuItemDodajClana = new javax.swing.JMenuItem();
        jMenuItemPregledClana = new javax.swing.JMenuItem();
        jMenuKnjiga = new javax.swing.JMenu();
        jMenuItemDodajKnjigu = new javax.swing.JMenuItem();
        jMenuItemPregledKnjige = new javax.swing.JMenuItem();
        jMenuPozajmica = new javax.swing.JMenu();
        jMenuItemDodajPozajmicu = new javax.swing.JMenuItem();
        jMenuItemPregledPozajmice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ulogovan je bibliotekar: ");

        jLabelUlogovani.setText("L");

        jMenuClan.setText("Član");

        jMenuItemDodajClana.setText("Dodaj");
        jMenuItemDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajClanaActionPerformed(evt);
            }
        });
        jMenuClan.add(jMenuItemDodajClana);

        jMenuItemPregledClana.setText("Pregled");
        jMenuItemPregledClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledClanaActionPerformed(evt);
            }
        });
        jMenuClan.add(jMenuItemPregledClana);

        jMenuBar1.add(jMenuClan);

        jMenuKnjiga.setText("Knjiga");

        jMenuItemDodajKnjigu.setText("Dodaj");
        jMenuItemDodajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajKnjiguActionPerformed(evt);
            }
        });
        jMenuKnjiga.add(jMenuItemDodajKnjigu);

        jMenuItemPregledKnjige.setText("Pregled");
        jMenuItemPregledKnjige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledKnjigeActionPerformed(evt);
            }
        });
        jMenuKnjiga.add(jMenuItemPregledKnjige);

        jMenuBar1.add(jMenuKnjiga);

        jMenuPozajmica.setText("Pozajmica");

        jMenuItemDodajPozajmicu.setText("Dodaj");
        jMenuItemDodajPozajmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajPozajmicuActionPerformed(evt);
            }
        });
        jMenuPozajmica.add(jMenuItemDodajPozajmicu);

        jMenuItemPregledPozajmice.setText("Pregled");
        jMenuItemPregledPozajmice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPregledPozajmiceActionPerformed(evt);
            }
        });
        jMenuPozajmica.add(jMenuItemPregledPozajmice);

        jMenuBar1.add(jMenuPozajmica);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabelUlogovani)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUlogovani))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPregledClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledClanaActionPerformed
        Cordinator.getInstance().otvoriPrikazClanovaFormu();
    }//GEN-LAST:event_jMenuItemPregledClanaActionPerformed

    private void jMenuItemDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajClanaActionPerformed
        Cordinator.getInstance().otvoriDodajClanaFormu();
    }//GEN-LAST:event_jMenuItemDodajClanaActionPerformed

    private void jMenuItemPregledKnjigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledKnjigeActionPerformed
        Cordinator.getInstance().otvoriPrikazKnjigaFormu();
    }//GEN-LAST:event_jMenuItemPregledKnjigeActionPerformed

    private void jMenuItemDodajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajKnjiguActionPerformed
        Cordinator.getInstance().otvoriDodajKnjiguFormu();
    }//GEN-LAST:event_jMenuItemDodajKnjiguActionPerformed

    private void jMenuItemDodajPozajmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajPozajmicuActionPerformed
        Cordinator.getInstance().otvoriDodajPozajmicuFormu();
    }//GEN-LAST:event_jMenuItemDodajPozajmicuActionPerformed

    private void jMenuItemPregledPozajmiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPregledPozajmiceActionPerformed
        Cordinator.getInstance().otvoriPrikazPozajmicaFormu();
    }//GEN-LAST:event_jMenuItemPregledPozajmiceActionPerformed

    public JLabel getjLabelUlogovani() {
        return jLabelUlogovani;
    }

    public void setjLabelUlogovani(JLabel jLabelUlogovani) {
        this.jLabelUlogovani = jLabelUlogovani;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClan;
    private javax.swing.JMenuItem jMenuItemDodajClana;
    private javax.swing.JMenuItem jMenuItemDodajKnjigu;
    private javax.swing.JMenuItem jMenuItemDodajPozajmicu;
    private javax.swing.JMenuItem jMenuItemPregledClana;
    private javax.swing.JMenuItem jMenuItemPregledKnjige;
    private javax.swing.JMenuItem jMenuItemPregledPozajmice;
    private javax.swing.JMenu jMenuKnjiga;
    private javax.swing.JMenu jMenuPozajmica;
    // End of variables declaration//GEN-END:variables
}
