/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Clan;
import domen.Knjiga;
import domen.Primerak;
import java.util.ArrayList;
import komunikacija.Operacije;
import komunikacija.Komunikacija;
import komunikacija.Zahtev;
import komunikacija.Odgovor;

/**
 *
 * @author milic
 */
public class PozajmicaForma extends javax.swing.JFrame {

    /**
     * Creates new form PozajmicaForma
     */
    public PozajmicaForma() {
        initComponents();
        setLocationRelativeTo(null);
        popuniClanove();
        popuniKnjige();
        popuniPrimerke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbClan = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPrimerak = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbKnjiga = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clan:");

        jLabel2.setText("Primerak:");

        jLabel3.setText("Knjiga:");

        jLabel4.setText("Datum uzimanja:");

        jLabel5.setText("Datum vracanja:");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbClan, 0, 227, Short.MAX_VALUE)
                    .addComponent(cmbPrimerak, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbKnjiga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPrimerak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbClan;
    private javax.swing.JComboBox cmbKnjiga;
    private javax.swing.JComboBox cmbPrimerak;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void popuniClanove() {
      /*  Zahtev kz = new Zahtev();
        kz.setOperacija(Operacije.VRATI_CLANOVE);

        Komunikacija.getInstance().posaljiZahtev(kz);
        Odgovor so = Komunikacija.getInstance().primiOdgovor();

        ArrayList<Clan> clanovi = (ArrayList<Clan>) so.getOdgovor();

        cmbClan.removeAllItems();

        for (Clan clan : clanovi) {
            cmbClan.addItem(clan);
        }*/

    }

    private void popuniKnjige() {
        /*Zahtev kz = new Zahtev();
        kz.setOperacija(Operacije.VRATI_KNJIGE);

        Komunikacija.getInstance().posaljiZahtev(kz);

        Odgovor so = Komunikacija.getInstance().primiOdgovor();
        ArrayList<Knjiga> knjige = (ArrayList<Knjiga>) so.getOdgovor();

        cmbKnjiga.removeAllItems();

        for (Knjiga knjiga : knjige) {
            cmbKnjiga.addItem(knjiga);
        }
*/
    }

    private void popuniPrimerke() {
      /*  Zahtev kz = new Zahtev();
        kz.setOperacija(Operacije.VRATI_PRIMERKE);

        Komunikacija.getInstance().posaljiZahtev(kz);

        Odgovor so = Komunikacija.getInstance().primiOdgovor();
        ArrayList<Primerak> primerci = (ArrayList<Primerak>) so.getOdgovor();

        cmbPrimerak.removeAllItems();

        for (Primerak primerak : primerci) {
            cmbPrimerak.addItem(primerak);
        }*/

    }

}
